---
- name: Install and configure Apache
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: start httpd
      service :
         name: apache2
         state: started
    - name: deploy index.html
      copy :
          src: index.html
          dest: /var/www/html/
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
