---
- name: Install and configure Apache Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present
      become: yes
    - name: Download Apache Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz"
        dest: /tmp/apache-tomcat.tar.gz
    - name: Extract Tomcat archive
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/apache-tomcat-9.0.80
    - name: Create a symbolic link
      file:
        src: /opt/apache-tomcat-9.0.80
        dest: /opt/tomcat
        state: link
    - name: Start Tomcat service
      shell: /opt/tomcat/bin/startup.sh
      ignore_errors: yes
